#!/usr/bin/env bash
# Copyright (c) 2011 Nick Bargnesi <nick@den-4.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

GO="true"
echo "Watching for changes in: $@"
while [ "${GO}" == "true" ]; do
    echo
    echo "[WAITING FOR CHANGES]"
    echo
    gate $@ && clear && make -j --silent --no-print-directory;
    if [ $? -eq 1 ]; then
        GO="false"
    fi
done

