#!/usr/bin/env bash
# Copyright (c) 2011 Nick Bargnesi <nick@den-4.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Prints all but the line specified by $1 from the standard input.
# Examples:
#   > echo -en "a\nb\nc\n" | line 2
#   > a
#   > c
#
if [ -z "$1" ]; then
    while read input; do
        echo $input
    done
else
    declare -i FIELD=$1
    grep '^.*$' -n --color=never | grep -v "^${FIELD}:" | sed "s/^[1-9][0-9]*://g"
fi

