#!/usr/bin/env bash
# Copyright (c) 2011-2014 Nick Bargnesi
# 
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

# Set urgency level
if [ ! -z "$1" ]; then
    if [ "$1" = "low" ]; then
        LEVEL="low"
        shift
    elif [ "$1" = "normal" ]; then
        LEVEL="normal"
        shift
    elif [ "$1" = "critical" ]; then
        LEVEL="critical"
        shift
    fi
fi
if [ -z "$LEVEL" ]; then
    LEVEL="normal"
fi

# Check for $# is 2 - summary & body
if [ ! $# -eq 2 ]; then
    echo -en "Usage: $0 [low,normal,critical] <summary> <body>\n"
    exit 1
fi

notify-send --expire-time=5000 --urgency=$LEVEL "$@"
