#!/usr/bin/env bash
# Copyright (c) 2011-2014 Nick Bargnesi
# 
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# Step through the list of modified files within a subversion tree, allowing
# the user to revert each one.
#
if [ -z "$(svn info)" ]; then
    echo -en "This does not appear to be a subversion-controlled tree, svn info returns nothing.\n"
    exit 1
fi

FILE="svn-interactive-temp-file"
svn status | grep "^M " | awk '{ print $2 }' > $FILE
for modifiedFile in $(cat $FILE); do
    echo -en "Revert ${modifiedFile} (y/n)? "
    read INPUT
    if [ "$INPUT" == "y" ]; then
        svn revert "$modifiedFile"
    fi
done
rm $FILE
