#!/usr/bin/env bash
# Copyright (c) 2011 Nick Bargnesi <nick@den-4.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Step through the list of unversioned files within a subversion tree, allowing
# the user to remove each one.
#
cleanup() {
    rm -f "${FILE}"
}

if [ -z "$(svn info)" ]; then
    echo -en "This does not appear to be a subversion-controlled tree, svn info returns nothing.\n"
    exit 1
fi

trap "cleanup; exit 1" SIGINT
FILE=$(mktemp)
svn status | grep "^? " | awk '{ print $2 }' > $FILE
for unversionedFile in $(cat $FILE); do
    echo -en "Remove ${unversionedFile} (y/n)? "
    read INPUT
    if [ "$INPUT" == "y" ]; then
        rm -fr "${unversionedFile}"
    fi
done
cleanup
